export const SAVE_INSTANCE = 'SAVE_INSTANCE';
export const SAVE_ALL_INSTANCE = 'SAVE_ALL_INSTANCE';
export const UPDATE_INSTANCE = 'UPDATE_INSTANCE';
export const DELETE_INSTANCE = 'DELETE_INSTANCE';
export const DELETE_ALL_INSTANCE = 'DELETE_ALL_INSTANCE';
